version: '3.8'

services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: feegow_clinic_app
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db
#     environment:
#       - DB_CONNECTION=mysql
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_DATABASE=feegow_clinic
#       - DB_USERNAME=root
#       - DB_PASSWORD=root
    # entrypoint: >
    #   sh -c "
    #   php artisan migrate --force &&
    #   apache2-foreground
    #   "

  db:
    image: mysql:8.0
    container_name: feegow_clinic_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feegow_clinic
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
